### ISSUE TITLE
一个小小的问题，请您一定要帮帮我！

### ISSUE THREAD

**Issue by WRMYX** [CJA-OS/CE-RAMOS#1]
用wimbuilder2制作怎么PE拥有UWP，rectify11怎么加入PE中，抱歉可能会打扰你一会时间，但请求你帮帮我，现在就您的RAMOS最好用了，如果有时间的话请帮帮我，愿您能看见和理解我。如果你成功的帮助了我我也可以给你一下20CNY的金额。但是您一定要帮帮我！

**Comment by CJA-OS** [comment]
## 你好
请加QQ：3148038763😊
