### ISSUE TITLE
关于蓝牙的问题

### ISSUE THREAD

**Issue by dm192** [CJA-OS/CE-RAMOS#2]
我在使用这个系统的时候蓝牙不可用，或者说可以开关，但无法扫描和连接，但是我有时候需要使用蓝牙功能，所以可不可以加入蓝牙支持？

**Comment by CJA-OS** [comment]
首先，感谢您打开的issue🙂
我们在当前版本中确实没有增加蓝牙功能
后面我们可能会增加一个新版本以支持蓝牙等更多功能（大小约在1.6~1.7GB之间）
